### ISSUE TITLE
"docker login" fails, token issued, but use fails?

### ISSUE THREAD

**Issue by skandragon** [bitnami/bitnami-docker-harbor-portal#7] opened 2020-07-10 23:39 UTC
**Description**

On a newly installed docker-compose based run, I am unable to authenticate.

I have an nginx configured to terminate the SSL connection, and believe it is configured to pass traffic properly to the then HTTP-based harbor-nginx container listening on 127.0.0.1:8082

**Steps to reproduce the issue:**

1.  Install
1. Change the machine port for nginx to listen on 127.0.0.1:8083
1. Change the endpoint in the yaml and the registry config's token uri to be https://docker.flame.org as a base.
1. Remove the marked lines from the nginx yaml to comment out `proxy_set_header X-Forwarded-Proto $scheme;` (this is added by the front-end ssl-terminating server, which only accepts ssl)
1. Create a user with a password, and assign it to a pushable role on the 'library' project.

```
$ ack X-Forwarded-Proto
52:      #proxy_set_header X-Forwarded-Proto $scheme;
65:      #proxy_set_header X-Forwarded-Proto $scheme;
78:      #proxy_set_header X-Forwarded-Proto $scheme;
91:      #proxy_set_header X-Forwarded-Proto $scheme;
108:      #proxy_set_header X-Forwarded-Proto $scheme;
121:      #proxy_set_header X-Forwarded-Proto $scheme;
```

**Describe the results you received:**

Docker login of a newly created user fails.

**Describe the results you expected:**

Docker login to work.  :)

I have verified the password is correct, and can log into the UI using it.

**Additional information you deem important (e.g. issue happens only occasionally):**

frontend -> harbor-nginx:

```
GET /v2/ HTTP/1.0
Host: docker.flame.org
X-Real-IP: 68.97.160.145
X-Forwarded-For: 68.97.160.145
X-Forwarded-Proto: https
Connection: close
User-Agent: docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))
Accept-Encoding: gzip
```

harbor-nginx -> registry:

```
GET /v2/ HTTP/1.1
Host: docker.flame.org
X-Real-IP: 172.26.0.1
X-Forwarded-For: 68.97.160.145, 172.26.0.1
Connection: close
X-Forwarded-Proto: https
User-Agent: docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))
Accept-Encoding: gzip
```

registry -> harbor-nginx:

```
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Set-Cookie: sid=b15b3368b6b100f508e8db75b14fcaf8; Path=/; HttpOnly
Www-Authenticate: Bearer realm="https://docker.flame.org/service/token",service="harbor-registry"
X-Request-Id: 5e390431-f0d2-40ff-8e46-aafdb967a429
Date: Fri, 10 Jul 2020 23:27:14 GMT
Content-Length: 76
Connection: close

{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized: unauthorized"}]}
```

harbor-nginx -> frontend:

```
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Fri, 10 Jul 2020 23:27:14 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 76
Connection: close
Docker-Distribution-Api-Version: registry/2.0
Set-Cookie: sid=b15b3368b6b100f508e8db75b14fcaf8; Path=/; HttpOnly
Www-Authenticate: Bearer realm="https://docker.flame.org/service/token",service="harbor-registry"
X-Request-Id: 5e390431-f0d2-40ff-8e46-aafdb967a429

{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized: unauthorized"}]}
```

frontend -> harbor-nginx:

```
GET /service/token?account=explorer&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.0
Host: docker.flame.org
X-Real-IP: 68.97.160.145
X-Forwarded-For: 68.97.160.145
X-Forwarded-Proto: https
Connection: close
User-Agent: docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))
Authorization: Basic REDACTED
Accept-Encoding: gzip
```

harbor-nginx -> registry:

```
GET /service/token?account=explorer&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.1
Host: docker.flame.org
X-Real-IP: 172.26.0.1
X-Forwarded-For: 68.97.160.145, 172.26.0.1
Connection: close
X-Forwarded-Proto: https
User-Agent: docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))
Authorization: Basic REDACTED
Accept-Encoding: gzip
```

registry -> harbor-nginx:

```
HTTP/1.1 200 OK
Content-Length: 1109
Content-Type: application/json; charset=utf-8
Set-Cookie: sid=177e6c0a0e0533bf4ca938ea166091ae; Path=/; HttpOnly
X-Request-Id: d2636fd2-2860-4e0b-8989-c8866bf28c10
Date: Fri, 10 Jul 2020 23:27:15 GMT
Connection: close

{"token":"REDACTED","access_token":"","expires_in":1800,"issued_at":"2020-07-10T23:27:15Z"}
```

harbor-nginx -> frontend:

```
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 10 Jul 2020 23:27:15 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1109
Connection: close
Set-Cookie: sid=177e6c0a0e0533bf4ca938ea166091ae; Path=/; HttpOnly
X-Request-Id: d2636fd2-2860-4e0b-8989-c8866bf28c10

{"token":"REDACTED","access_token":"","expires_in":1800,"issued_at":"2020-07-10T23:27:15Z"}
```

frontend -> harbor-nginx:

```
GET /v2/ HTTP/1.0
Host: docker.flame.org
X-Real-IP: 68.97.160.145
X-Forwarded-For: 68.97.160.145
X-Forwarded-Proto: https
Connection: close
User-Agent: docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))
Authorization: Bearer REDACTED, but matches the token returned above
Accept-Encoding: gzip
```

harbor-nginx -> registry:

```
GET /v2/ HTTP/1.1
Host: docker.flame.org
X-Real-IP: 172.26.0.1
X-Forwarded-For: 68.97.160.145, 172.26.0.1
Connection: close
X-Forwarded-Proto: https
User-Agent: docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))
Authorization: Bearer REDACTED
Accept-Encoding: gzip
```

registry -> harbor-nginx:

```
HTTP/1.1 401 Unauthorized
Content-Length: 87
Content-Type: application/json; charset=utf-8
Date: Fri, 10 Jul 2020 23:27:15 GMT
Docker-Distribution-Api-Version: registry/2.0
Set-Cookie: sid=3faa46ab6da11ee64acf984aa15b9675; Path=/; HttpOnly
Www-Authenticate: Bearer realm="https://docker.flame.org/service/token",service="harbor-registry"
X-Request-Id: f46e7ca5-8fd9-438b-8b93-18a3cd78c676
Connection: close

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

harbor-nginx -> frontend:

```
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Fri, 10 Jul 2020 23:27:15 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 87
Connection: close
Docker-Distribution-Api-Version: registry/2.0
Set-Cookie: sid=3faa46ab6da11ee64acf984aa15b9675; Path=/; HttpOnly
Www-Authenticate: Bearer realm="https://docker.flame.org/service/token",service="harbor-registry"
X-Request-Id: f46e7ca5-8fd9-438b-8b93-18a3cd78c676

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 28
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-40-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.774GiB
 Name: docker01.flame.org
 ID: LG3F:FNLA:I4LG:UQKI:MJIS:GD7V:TZZZ:VPST:EOW2:NJGJ:2MQU:EX4A
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker host info:

```
Linux docker01.flame.org 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by skandragon** [comment] 2020-07-10 23:49
I do see this in 'core' logs:

```failed to authenticate explorer: Failed to authenticate user, due to error 'Invalid credentials'```

I am sure however I have the proper creds, and both the admin and 'explorer' userids can log into the UI.

**Comment by juan131** [comment] 2020-07-13 06:41
Hi @skandragon 

Closing it as a duplicate of https://github.com/bitnami/bitnami-docker-harbor-portal/issues/4

We're already discussing this problem in a different issue. Let's move the conversation there to avoid duplication.

**Closed by juan131** 2020-07-13 06:41 UTC

**Comment by skandragon** [comment] 2020-07-14 00:04
I do not believe this is related to the issue in #4.  It seems like that issue is related to insecure repositories, using the proper password, and so on.  The issue I'm reporting is where Docker connects, gets a token, and it fails when it tries to use it.
